import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// app/layout.tsx
import { Noto_Sans_JP } from "next/font/google";
import Analytics from "./components/Analytics";

const notoSansJp = Noto_Sans_JP({
  subsets: ["latin"], // 日本語含めたい場合は ['latin', 'japanese'] ではなく、['latin']でOK
  display: "swap",
  weight: ["400", "700"], // 必要に応じて
  variable: "--font-noto-sans-jp", // カスタムプロパティ
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Growbase Lab - 未経験からIT転職",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <head suppressHydrationWarning>
        <Analytics />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSansJp.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
